In [1]:
import yt
import numpy as np
import yt.units as u

In [2]:
ds = yt.load("/Users/astrocomnyc/Desktop/FIRE_M12i_ref11/snapshot_600.hdf5")

yt : [INFO     ] 2017-06-20 11:44:47,448 Calculating time from 1.000e+00 to be 4.355e+17 seconds
yt : [INFO     ] 2017-06-20 11:44:47,450 Assuming length units are in kpc/h (comoving)
yt : [INFO     ] 2017-06-20 11:44:47,488 Parameters: current_time              = 4.35455710881e+17 s
yt : [INFO     ] 2017-06-20 11:44:47,490 Parameters: domain_dimensions         = [2 2 2]
yt : [INFO     ] 2017-06-20 11:44:47,497 Parameters: domain_left_edge          = [ 0.  0.  0.]
yt : [INFO     ] 2017-06-20 11:44:47,500 Parameters: domain_right_edge         = [ 60000.  60000.  60000.]
yt : [INFO     ] 2017-06-20 11:44:47,503 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2017-06-20 11:44:47,504 Parameters: current_redshift          = 0.0
yt : [INFO     ] 2017-06-20 11:44:47,507 Parameters: omega_lambda              = 0.728
yt : [INFO     ] 2017-06-20 11:44:47,513 Parameters: omega_matter              = 0.272
yt : [INFO     ] 2017-06-20 11:44:47,516 Parameters: hubble_constant           = 0

In [3]:
cd Desktop

/Users/astrocomnyc/Desktop


In [4]:
import practiceFunction

In [9]:
reload(practiceFunction)

<module 'practiceFunction' from 'practiceFunction.py'>

In [11]:
practiceFunction.practice(ds,w=75.0)

yt : [INFO     ] 2017-06-20 15:48:20,870 Max Value is 1.30128e+02 at 29286.1032485961914062 31049.2944717407226562 32589.5833969116210938


[ 29286.1032486   31049.29447174  32589.58339691] code_length
48
[ 0.29296875  0.29296875  0.29296875] kpc
[ 0.08583069  0.08583069  0.08583069] kpc**2
[ 4.11987305  4.11987305  4.11987305] kpc**2


/anaconda/lib/python2.7/site-packages/matplotlib/tight_layout.py:222: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
yt : [INFO     ] 2017-06-20 15:50:31,188 Saving plot Tester2.png


In [8]:
practiceFunction.practice(ds,a=45.0,b=45.0,c=45.0)

yt : [INFO     ] 2017-06-20 11:57:53,681 Max Value is 1.30128e+02 at 29286.1032485961914062 31049.2944717407226562 32589.5833969116210938


[ 29286.1032486   31049.29447174  32589.58339691] code_length
[ 45.  45.  45.] kpc
45.0
[[  5.46408588e+12   5.46408588e+12   5.46408588e+12 ...,   2.89100419e+17
    2.89100419e+17   2.89100419e+17]
 [  5.46408588e+12   5.46408588e+12   5.46408588e+12 ...,   2.89100419e+17
    2.89100419e+17   2.89100419e+17]
 [  5.46408588e+12   5.46408588e+12   5.46408588e+12 ...,   2.89100419e+17
    2.89100419e+17   2.89100419e+17]
 ..., 
 [  2.68026970e+12   2.68026970e+12   2.68026970e+12 ...,   7.80750199e+12
    7.80750199e+12   7.80750199e+12]
 [  2.68026970e+12   2.68026970e+12   2.68026970e+12 ...,   7.80750199e+12
    7.80750199e+12   7.80750199e+12]
 [  2.68026970e+12   2.68026970e+12   2.68026970e+12 ...,   7.80750199e+12
    7.80750199e+12   7.80750199e+12]] cm**(-2)
[[False False False ..., False False False]
 [False False False ..., False False False]
 [False False False ..., False False False]
 ..., 
 [False False False ..., False False False]
 [False False False ..., False False Fal