In [41]:
import yt
import numpy as np
import yt.units as u

In [42]:
ds = yt.load("/Users/astrocomnyc/Desktop/FIRE_M12i_ref11/snapshot_600.hdf5")

yt : [INFO     ] 2017-06-20 15:21:31,171 Calculating time from 1.000e+00 to be 4.355e+17 seconds
yt : [INFO     ] 2017-06-20 15:21:31,173 Assuming length units are in kpc/h (comoving)
yt : [INFO     ] 2017-06-20 15:21:31,187 Parameters: current_time              = 4.35455710881e+17 s
yt : [INFO     ] 2017-06-20 15:21:31,188 Parameters: domain_dimensions         = [2 2 2]
yt : [INFO     ] 2017-06-20 15:21:31,189 Parameters: domain_left_edge          = [ 0.  0.  0.]
yt : [INFO     ] 2017-06-20 15:21:31,191 Parameters: domain_right_edge         = [ 60000.  60000.  60000.]
yt : [INFO     ] 2017-06-20 15:21:31,193 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2017-06-20 15:21:31,194 Parameters: current_redshift          = 0.0
yt : [INFO     ] 2017-06-20 15:21:31,197 Parameters: omega_lambda              = 0.728
yt : [INFO     ] 2017-06-20 15:21:31,200 Parameters: omega_matter              = 0.272
yt : [INFO     ] 2017-06-20 15:21:31,204 Parameters: hubble_constant           = 0

In [43]:
val,loc=ds.find_max(('gas','H_number_density'))

yt : [INFO     ] 2017-06-20 15:21:33,489 Allocating for 4.787e+06 particles (index particle type 'all')
yt : [INFO     ] 2017-06-20 15:21:34,287 Identified 3.468e+05 octs
yt : [INFO     ] 2017-06-20 15:22:11,038 Max Value is 1.30128e+02 at 29286.1032485961914062 31049.2944717407226562 32589.5833969116210938


In [44]:
a=loc.in_units("code_length")

In [5]:
print a

[ 29286.1032486   31049.29447174  32589.58339691] code_length


In [51]:
width_array=(ds.arr([75.0,75.0,75.0],"kpc")).in_units("code_length")
print width_array

[ 52.65  52.65  52.65] code_length


In [66]:
dir(ds)

['__class__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattribute__',
 '__getitem__',
 '__hash__',
 '__init__',
 '__iter__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_add_object_class',
 '_arr',
 '_create_unit_registry',
 '_field_info_class',
 '_field_spec',
 '_file_class',
 '_get_field_info',
 '_get_hvals',
 '_get_uvals',
 '_guess_candidates',
 '_hash',
 '_header_spec',
 '_index_class',
 '_index_proxy',
 '_instantiated',
 '_instantiated_index',
 '_is_valid',
 '_last_finfo',
 '_last_freq',
 '_mrep',
 '_override_code_units',
 '_parse_parameter_file',
 '_particle_coordinates_name',
 '_particle_mass_name',
 '_particle_type_counts',
 '_particle_velocity_name',
 '_ptype_spec',
 '_quan',
 '_set_code_unit_attributes',
 '_set_derived_attrs',
 '_set_owls_eagle',
 '_set_owls_eagle_units',
 '_setup_binary_spec',
 '_setup_classes',
 '_setup_coordinate_handler',
 '_

In [69]:
ds.geometry

'cartesian'

In [52]:
L = ([ 29286.1032486,   31049.29447174, 0.0])
Npixels = 512

In [53]:
image = yt.off_axis_projection(ds, a, L, width_array, Npixels, ("gas","H_number_density"), no_ghost=False)

In [54]:
limit=image>2e20
print limit

[[False False False ..., False False False]
 [False False False ..., False False False]
 [False False False ..., False False False]
 ..., 
 [False False False ..., False False False]
 [False False False ..., False False False]
 [False False False ..., False False False]]


In [55]:
subtotal=(np.sum(limit))
print subtotal

256


[ 75.  75.  75.] kpc


In [56]:
pixel_len=(width_array/Npixels)

In [57]:
per_pixel=pixel_len.in_units("kpc")
print per_pixel

[ 0.14648438  0.14648438  0.14648438] kpc


In [58]:
area=per_pixel*per_pixel
print area

[ 0.02145767  0.02145767  0.02145767] kpc**2


In [59]:
total_area=area*subtotal
print total_area

[ 5.49316406  5.49316406  5.49316406] kpc**2


In [63]:
yt.write_projection(image, "Tester.png",
                    colorbar_label="Column Density (cm$^{-2}$)")

yt : [INFO     ] 2017-06-20 15:42:38,972 Saving plot Tester.png


'Tester.png'