In [1]:
import yt
import numpy as np
import yt.units as u

In [2]:
ds = yt.load("/Users/astrocomnyc/Desktop/FIRE_M12i_ref11/snapshot_600.hdf5")

yt : [INFO     ] 2017-06-20 12:13:34,201 Calculating time from 1.000e+00 to be 4.355e+17 seconds
yt : [INFO     ] 2017-06-20 12:13:34,202 Assuming length units are in kpc/h (comoving)
yt : [INFO     ] 2017-06-20 12:13:34,232 Parameters: current_time              = 4.35455710881e+17 s
yt : [INFO     ] 2017-06-20 12:13:34,236 Parameters: domain_dimensions         = [2 2 2]
yt : [INFO     ] 2017-06-20 12:13:34,238 Parameters: domain_left_edge          = [ 0.  0.  0.]
yt : [INFO     ] 2017-06-20 12:13:34,240 Parameters: domain_right_edge         = [ 60000.  60000.  60000.]
yt : [INFO     ] 2017-06-20 12:13:34,242 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2017-06-20 12:13:34,245 Parameters: current_redshift          = 0.0
yt : [INFO     ] 2017-06-20 12:13:34,247 Parameters: omega_lambda              = 0.728
yt : [INFO     ] 2017-06-20 12:13:34,251 Parameters: omega_matter              = 0.272
yt : [INFO     ] 2017-06-20 12:13:34,255 Parameters: hubble_constant           = 0

In [3]:
cd Desktop

/Users/astrocomnyc/Desktop


In [4]:
import practiceFunction

In [19]:
reload(practiceFunction)

<module 'practiceFunction' from 'practiceFunction.py'>

In [20]:
practiceFunction.practice(ds,w=75.0,Npixels=1024)

yt : [INFO     ] 2017-06-20 14:43:30,722 Max Value is 1.30128e+02 at 29286.1032485961914062 31049.2944717407226562 32589.5833969116210938


[ 29286.1032486   31049.29447174  32589.58339691] code_length
770
[ 0.07324219  0.07324219  0.07324219] kpc
[ 0.00536442  0.00536442  0.00536442] kpc**2
[ 4.13060188  4.13060188  4.13060188] kpc**2


In [21]:
practiceFunction.practice(ds,w=45.0,Npixels=1024)

yt : [INFO     ] 2017-06-20 14:46:52,960 Max Value is 1.30128e+02 at 29286.1032485961914062 31049.2944717407226562 32589.5833969116210938


[ 29286.1032486   31049.29447174  32589.58339691] code_length
2134
[ 0.04394531  0.04394531  0.04394531] kpc
[ 0.00193119  0.00193119  0.00193119] kpc**2
[ 4.12116051  4.12116051  4.12116051] kpc**2


In [9]:
practiceFunction.practice(ds, w=60.0,Npixels=1024)

yt : [INFO     ] 2017-06-20 12:22:00,860 Max Value is 1.30128e+02 at 29286.1032485961914062 31049.2944717407226562 32589.5833969116210938


[ 29286.1032486   31049.29447174  32589.58339691] code_length
[ 60.  60.  60.] kpc
60.0
[[  1.52265055e+13   1.52265055e+13   1.52265055e+13 ...,   3.29021388e+15
    3.29021388e+15   3.29021388e+15]
 [  1.52265055e+13   1.52265055e+13   1.52265055e+13 ...,   3.29021388e+15
    3.29021388e+15   3.29021388e+15]
 [  1.52265055e+13   1.52265055e+13   1.52265055e+13 ...,   3.29021388e+15
    3.29021388e+15   3.29021388e+15]
 ..., 
 [  2.86901427e+12   2.86901427e+12   2.86901427e+12 ...,   1.64728399e+13
    1.64728399e+13   1.64728399e+13]
 [  2.86901427e+12   2.86901427e+12   2.86901427e+12 ...,   1.64728399e+13
    1.64728399e+13   1.64728399e+13]
 [  2.86901427e+12   2.86901427e+12   2.86901427e+12 ...,   1.64728399e+13
    1.64728399e+13   1.64728399e+13]] cm**(-2)
[[False False False ..., False False False]
 [False False False ..., False False False]
 [False False False ..., False False False]
 ..., 
 [False False False ..., False False False]
 [False False False ..., False False Fal

In [10]:
practiceFunction.practice(ds, a=80.0,b=80.0,c=80.0,Npixels=1024)

yt : [INFO     ] 2017-06-20 12:25:12,035 Max Value is 1.30128e+02 at 29286.1032485961914062 31049.2944717407226562 32589.5833969116210938


[ 29286.1032486   31049.29447174  32589.58339691] code_length
[ 80.  80.  80.] kpc
80.0
[[  4.92509236e+13   4.92509236e+13   5.35890419e+13 ...,   1.42676434e+15
    1.42676434e+15   1.42676434e+15]
 [  4.92509236e+13   4.92509236e+13   5.35890419e+13 ...,   1.42676434e+15
    1.42676434e+15   1.42676434e+15]
 [  4.92509236e+13   4.92509236e+13   5.35890419e+13 ...,   1.42676434e+15
    1.42676434e+15   1.42676434e+15]
 ..., 
 [  2.71228783e+13   2.71228783e+13   2.66507873e+13 ...,   8.50180419e+13
    8.50180419e+13   8.50180419e+13]
 [  2.71228783e+13   2.71228783e+13   2.66507873e+13 ...,   8.50180419e+13
    8.50180419e+13   8.50180419e+13]
 [  2.71228783e+13   2.71228783e+13   2.66507873e+13 ...,   8.50180419e+13
    8.50180419e+13   8.50180419e+13]] cm**(-2)
[[False False False ..., False False False]
 [False False False ..., False False False]
 [False False False ..., False False False]
 ..., 
 [False False False ..., False False False]
 [False False False ..., False False Fal

In [22]:
practiceFunction.practice(ds,w=75.0,Npixels=256)

yt : [INFO     ] 2017-06-20 14:50:32,749 Max Value is 1.30128e+02 at 29286.1032485961914062 31049.2944717407226562 32589.5833969116210938


[ 29286.1032486   31049.29447174  32589.58339691] code_length
48
[ 0.29296875  0.29296875  0.29296875] kpc
[ 0.08583069  0.08583069  0.08583069] kpc**2
[ 4.11987305  4.11987305  4.11987305] kpc**2


In [23]:
practiceFunction.practice(ds,w=45.0,Npixels=256)

yt : [INFO     ] 2017-06-20 14:54:19,757 Max Value is 1.30128e+02 at 29286.1032485961914062 31049.2944717407226562 32589.5833969116210938


[ 29286.1032486   31049.29447174  32589.58339691] code_length
130
[ 0.17578125  0.17578125  0.17578125] kpc
[ 0.03089905  0.03089905  0.03089905] kpc**2
[ 4.01687622  4.01687622  4.01687622] kpc**2


In [13]:
practiceFunction.practice(ds, a=60.0,b=60.0,c=60.0,Npixels=256)

yt : [INFO     ] 2017-06-20 12:33:54,151 Max Value is 1.30128e+02 at 29286.1032485961914062 31049.2944717407226562 32589.5833969116210938


[ 29286.1032486   31049.29447174  32589.58339691] code_length
[ 60.  60.  60.] kpc
60.0
[[  1.52265055e+13   1.52265055e+13   1.52265055e+13 ...,   3.29021388e+15
    3.29021388e+15   3.29021388e+15]
 [  1.52265055e+13   1.52265055e+13   1.52265055e+13 ...,   3.29021388e+15
    3.29021388e+15   3.29021388e+15]
 [  1.52265055e+13   1.52265055e+13   1.52265055e+13 ...,   3.29021388e+15
    3.29021388e+15   3.29021388e+15]
 ..., 
 [  2.86901427e+12   2.86901427e+12   2.86901427e+12 ...,   1.64728399e+13
    1.64728399e+13   1.64728399e+13]
 [  2.86901427e+12   2.86901427e+12   2.86901427e+12 ...,   1.64728399e+13
    1.64728399e+13   1.64728399e+13]
 [  2.86901427e+12   2.86901427e+12   2.86901427e+12 ...,   1.64728399e+13
    1.64728399e+13   1.64728399e+13]] cm**(-2)
[[False False False ..., False False False]
 [False False False ..., False False False]
 [False False False ..., False False False]
 ..., 
 [False False False ..., False False False]
 [False False False ..., False False Fal

In [14]:
practiceFunction.practice(ds, a=80.0,b=80.0,c=80.0,Npixels=256)

yt : [INFO     ] 2017-06-20 12:36:45,483 Max Value is 1.30128e+02 at 29286.1032485961914062 31049.2944717407226562 32589.5833969116210938


[ 29286.1032486   31049.29447174  32589.58339691] code_length
[ 80.  80.  80.] kpc
80.0
[[  4.92509236e+13   4.92509236e+13   5.35890419e+13 ...,   1.42676434e+15
    1.42676434e+15   1.42676434e+15]
 [  4.92509236e+13   4.92509236e+13   5.35890419e+13 ...,   1.42676434e+15
    1.42676434e+15   1.42676434e+15]
 [  4.92509236e+13   4.92509236e+13   5.35890419e+13 ...,   1.42676434e+15
    1.42676434e+15   1.42676434e+15]
 ..., 
 [  2.71228783e+13   2.71228783e+13   2.66507873e+13 ...,   8.50180419e+13
    8.50180419e+13   8.50180419e+13]
 [  2.71228783e+13   2.71228783e+13   2.66507873e+13 ...,   8.50180419e+13
    8.50180419e+13   8.50180419e+13]
 [  2.71228783e+13   2.71228783e+13   2.66507873e+13 ...,   8.50180419e+13
    8.50180419e+13   8.50180419e+13]] cm**(-2)
[[False False False ..., False False False]
 [False False False ..., False False False]
 [False False False ..., False False False]
 ..., 
 [False False False ..., False False False]
 [False False False ..., False False Fal