In [1]:
import yt
import numpy as np
import yt.units as u

In [2]:
ds = yt.load("/Users/astrocomnyc/Desktop/FIRE_M12i_ref11/snapshot_600.hdf5")

yt : [INFO     ] 2017-06-19 15:07:21,591 Calculating time from 1.000e+00 to be 4.355e+17 seconds
yt : [INFO     ] 2017-06-19 15:07:21,592 Assuming length units are in kpc/h (comoving)
yt : [INFO     ] 2017-06-19 15:07:21,619 Parameters: current_time              = 4.35455710881e+17 s
yt : [INFO     ] 2017-06-19 15:07:21,620 Parameters: domain_dimensions         = [2 2 2]
yt : [INFO     ] 2017-06-19 15:07:21,622 Parameters: domain_left_edge          = [ 0.  0.  0.]
yt : [INFO     ] 2017-06-19 15:07:21,624 Parameters: domain_right_edge         = [ 60000.  60000.  60000.]
yt : [INFO     ] 2017-06-19 15:07:21,626 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2017-06-19 15:07:21,630 Parameters: current_redshift          = 0.0
yt : [INFO     ] 2017-06-19 15:07:21,633 Parameters: omega_lambda              = 0.728
yt : [INFO     ] 2017-06-19 15:07:21,636 Parameters: omega_matter              = 0.272
yt : [INFO     ] 2017-06-19 15:07:21,637 Parameters: hubble_constant           = 0

In [3]:
val,loc=ds.find_max(('gas','H_number_density'))

yt : [INFO     ] 2017-06-19 15:07:31,851 Allocating for 4.787e+06 particles (index particle type 'all')
yt : [INFO     ] 2017-06-19 15:07:32,797 Identified 3.468e+05 octs
yt : [INFO     ] 2017-06-19 15:08:11,302 Max Value is 1.30128e+02 at 29286.1032485961914062 31049.2944717407226562 32589.5833969116210938


In [4]:
a=loc.in_units("code_length")

In [14]:
print a

[ 29286.1032486   31049.29447174  32589.58339691] code_length


In [34]:
b=ds.arr([50.0,50.0,50.0],"kpc")
print b

[ 50.  50.  50.] kpc


In [37]:
d=b.in_units("code_length")
print c

[ 35.1  35.1  35.1] code_length


In [38]:
c = a
L = ([1.0,  0.0, 0.0])
W = d
Npixels = 512

In [39]:
image = yt.off_axis_projection(ds, c, L, W, Npixels, ("gas","H_number_density"), no_ghost=False)

In [40]:
print image

[[  6.14464287e+12   6.14464287e+12   6.14464287e+12 ...,   6.84099452e+17
    6.84099452e+17   6.84099452e+17]
 [  6.14464287e+12   6.14464287e+12   6.14464287e+12 ...,   6.84099452e+17
    6.84099452e+17   6.84099452e+17]
 [  6.14464287e+12   6.14464287e+12   6.14464287e+12 ...,   6.84099452e+17
    6.84099452e+17   6.84099452e+17]
 ..., 
 [  1.64526458e+12   1.64526458e+12   1.64526458e+12 ...,   7.79363555e+12
    7.79363555e+12   7.79363555e+12]
 [  1.64526458e+12   1.64526458e+12   1.64526458e+12 ...,   7.79363555e+12
    7.79363555e+12   7.79363555e+12]
 [  1.64526458e+12   1.64526458e+12   1.64526458e+12 ...,   7.79363555e+12
    7.79363555e+12   7.79363555e+12]] cm**(-2)


In [41]:
limit= image>2e20
print limit

[[False False False ..., False False False]
 [False False False ..., False False False]
 [False False False ..., False False False]
 ..., 
 [False False False ..., False False False]
 [False False False ..., False False False]
 [False False False ..., False False False]]


In [42]:
subtotal=(np.sum(limit))
print subtotal

425


In [45]:
ab=d/512
print ab

[ 0.06855469  0.06855469  0.06855469] code_length


In [13]:
#change to unit
#take the center value 
#two center value and one zero
#to get the same value as the x,y,z
#on access
#

u'/Users/astrocomnyc'

In [46]:
pixel=ab.in_units("kpc")

In [47]:
print pixel

[ 0.09765625  0.09765625  0.09765625] kpc


In [49]:
area=pixel*pixel
print area

[ 0.00953674  0.00953674  0.00953674] kpc**2


In [50]:
total=subtotal*area
print total

[ 4.05311584  4.05311584  4.05311584] kpc**2
