In [1]:
import yt
import numpy as np
import yt.units as u

In [2]:
ds = yt.load("/Users/astrocomnyc/Desktop/FIRE_M12i_ref11/snapshot_600.hdf5")

yt : [INFO     ] 2017-06-20 11:40:44,893 Calculating time from 1.000e+00 to be 4.355e+17 seconds
yt : [INFO     ] 2017-06-20 11:40:44,894 Assuming length units are in kpc/h (comoving)
yt : [INFO     ] 2017-06-20 11:40:44,932 Parameters: current_time              = 4.35455710881e+17 s
yt : [INFO     ] 2017-06-20 11:40:44,934 Parameters: domain_dimensions         = [2 2 2]
yt : [INFO     ] 2017-06-20 11:40:44,938 Parameters: domain_left_edge          = [ 0.  0.  0.]
yt : [INFO     ] 2017-06-20 11:40:44,939 Parameters: domain_right_edge         = [ 60000.  60000.  60000.]
yt : [INFO     ] 2017-06-20 11:40:44,941 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2017-06-20 11:40:44,943 Parameters: current_redshift          = 0.0
yt : [INFO     ] 2017-06-20 11:40:44,946 Parameters: omega_lambda              = 0.728
yt : [INFO     ] 2017-06-20 11:40:44,947 Parameters: omega_matter              = 0.272
yt : [INFO     ] 2017-06-20 11:40:44,949 Parameters: hubble_constant           = 0

In [5]:
cd Desktop

/Users/astrocomnyc/Desktop


In [13]:
import practiceFunction

In [18]:
reload(practiceFunction)

<module 'practiceFunction' from 'practiceFunction.py'>

In [19]:
practiceFunction.practice(ds)

yt : [INFO     ] 2017-06-20 11:50:33,636 Max Value is 1.30128e+02 at 29286.1032485961914062 31049.2944717407226562 32589.5833969116210938


[ 29286.1032486   31049.29447174  32589.58339691] code_length
[ 50.  50.  50.] kpc
50.0
[[  6.14464287e+12   6.14464287e+12   6.14464287e+12 ...,   6.84099452e+17
    6.84099452e+17   6.84099452e+17]
 [  6.14464287e+12   6.14464287e+12   6.14464287e+12 ...,   6.84099452e+17
    6.84099452e+17   6.84099452e+17]
 [  6.14464287e+12   6.14464287e+12   6.14464287e+12 ...,   6.84099452e+17
    6.84099452e+17   6.84099452e+17]
 ..., 
 [  1.64526458e+12   1.64526458e+12   1.64526458e+12 ...,   7.79363555e+12
    7.79363555e+12   7.79363555e+12]
 [  1.64526458e+12   1.64526458e+12   1.64526458e+12 ...,   7.79363555e+12
    7.79363555e+12   7.79363555e+12]
 [  1.64526458e+12   1.64526458e+12   1.64526458e+12 ...,   7.79363555e+12
    7.79363555e+12   7.79363555e+12]] cm**(-2)
[[False False False ..., False False False]
 [False False False ..., False False False]
 [False False False ..., False False False]
 ..., 
 [False False False ..., False False False]
 [False False False ..., False False Fal

In [20]:
practiceFunction.practice(ds,a=80.0,b=80.0,c=80.0)

yt : [INFO     ] 2017-06-20 11:54:35,513 Max Value is 1.30128e+02 at 29286.1032485961914062 31049.2944717407226562 32589.5833969116210938


[ 29286.1032486   31049.29447174  32589.58339691] code_length
[ 80.  80.  80.] kpc
80.0
[[  4.92509236e+13   4.92509236e+13   5.35890419e+13 ...,   1.42676434e+15
    1.42676434e+15   1.42676434e+15]
 [  4.92509236e+13   4.92509236e+13   5.35890419e+13 ...,   1.42676434e+15
    1.42676434e+15   1.42676434e+15]
 [  4.92509236e+13   4.92509236e+13   5.35890419e+13 ...,   1.42676434e+15
    1.42676434e+15   1.42676434e+15]
 ..., 
 [  2.71228783e+13   2.71228783e+13   2.66507873e+13 ...,   8.50180419e+13
    8.50180419e+13   8.50180419e+13]
 [  2.71228783e+13   2.71228783e+13   2.66507873e+13 ...,   8.50180419e+13
    8.50180419e+13   8.50180419e+13]
 [  2.71228783e+13   2.71228783e+13   2.66507873e+13 ...,   8.50180419e+13
    8.50180419e+13   8.50180419e+13]] cm**(-2)
[[False False False ..., False False False]
 [False False False ..., False False False]
 [False False False ..., False False False]
 ..., 
 [False False False ..., False False False]
 [False False False ..., False False Fal

In [21]:
practiceFunction.practice(ds, a=60.0,b=60.0,c=60.0)

yt : [INFO     ] 2017-06-20 11:58:17,739 Max Value is 1.30128e+02 at 29286.1032485961914062 31049.2944717407226562 32589.5833969116210938


[ 29286.1032486   31049.29447174  32589.58339691] code_length
[ 60.  60.  60.] kpc
60.0
[[  1.52265055e+13   1.52265055e+13   1.52265055e+13 ...,   3.29021388e+15
    3.29021388e+15   3.29021388e+15]
 [  1.52265055e+13   1.52265055e+13   1.52265055e+13 ...,   3.29021388e+15
    3.29021388e+15   3.29021388e+15]
 [  1.52265055e+13   1.52265055e+13   1.52265055e+13 ...,   3.29021388e+15
    3.29021388e+15   3.29021388e+15]
 ..., 
 [  2.86901427e+12   2.86901427e+12   2.86901427e+12 ...,   1.64728399e+13
    1.64728399e+13   1.64728399e+13]
 [  2.86901427e+12   2.86901427e+12   2.86901427e+12 ...,   1.64728399e+13
    1.64728399e+13   1.64728399e+13]
 [  2.86901427e+12   2.86901427e+12   2.86901427e+12 ...,   1.64728399e+13
    1.64728399e+13   1.64728399e+13]] cm**(-2)
[[False False False ..., False False False]
 [False False False ..., False False False]
 [False False False ..., False False False]
 ..., 
 [False False False ..., False False False]
 [False False False ..., False False Fal